controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  effort_joint_controller:
    type: effort_controllers/JointVelocityController
    left_front: left_front_joint
    right_front: right_front_joint
    left_back: left_back_joint
    right_back: right_back_joint
    pid: { p: 0.1, i: 0.0, d: 0.0}